# By Abdullah As-Sadeed

name: bitscoper_cyber_toolbox
description: "Bitscoper Cyber ToolBox"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  async: any
  crypto: ^3.0.3
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_traceroute: ^0.0.1+2
  fluttertoast: ^8.2.4
  html: ^0.15.4
  http: ^1.2.1
  tcp_scanner: ^2.0.5
  url_launcher: ^6.2.5
  whois: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  rename: ^3.0.2

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  android: true
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
  ios: true
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 192
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#424242"
