# By Abdullah As-Sadeed

name: bitscoper-cyber-toolbox
title: Bitscoper Cyber ToolBox
summary: Bitscoper Cyber ToolBox
icon: assets/icon/maskable_icon_x512.png
description: A Flutter application consisting of TCP Port Scanner, Route Tracer, File Hash Calculator, String Encoder, Series URI Crawler, DNS Record Retriever, and WHOIS Retriever.
license: GPL-3.0
source-code: https://github.com/bitscoper/Bitscoper_Cyber_ToolBox/
website: https://github.com/bitscoper/Bitscoper_Cyber_ToolBox/
contact: https://github.com/bitscoper/Bitscoper_Cyber_ToolBox/
issues: https://github.com/bitscoper/Bitscoper_Cyber_ToolBox/issues/
donation: https://github.com/bitscoper/
type: app
confinement: strict
# compression: xz
grade: stable
base: core22
version: 8.0.2
slots:
  bitscoper-cyber-toolbox:
    interface: dbus
    bus: session
    name: bitscoper.bitscoper_cyber_toolbox
apps:
  bitscoper-cyber-toolbox:
    command: bitscoper_cyber_toolbox
    extensions: [gnome]
    plugs:
    - network
    slots:
      - dbus-bitscoper-cyber-toolbox
parts:
  bitscoper-cyber-toolbox:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
