# By Abdullah As-Sadeed

name: Build and Release
on:
  push:
    branches: ["main"]
jobs:
  build-for-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y ninja-build libgtk-3-dev

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Get Dependencies
        run: flutter pub get

      - name: Build for Linux
        run: flutter build linux --release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux Application
          path: build/linux/x64/release/bundle/*

  build-for-android:
    name: Build for Android
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APKs
        run: flutter build apk --split-per-abi --release

      - name: Build appbundle
        run: flutter build appbundle --release

      - name: Upload Build Artifacts (appbundle)
        uses: actions/upload-artifact@v4
        with:
          name: Android appbundle
          path: build/app/outputs/bundle/release/*

      - name: Upload Build Artifacts (APKs)
        uses: actions/upload-artifact@v4
        with:
          name: Android APKs
          path: build/app/outputs/flutter-apk/*

  build-for-macos:
    name: Build for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Get Dependencies
        run: flutter pub get

      - name: Build for macOS
        run: flutter build macos --release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macOS Application
          path: build/macos/Build/Products/Release/*.app

  # build-for-ios:
  #   name: Build for iOS
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Install Pods
  #       run: |
  #         cd ios && pod install

  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: "stable"

  #     - name: Run flutter doctor
  #       run: flutter doctor -v

  #     - name: Get Dependencies
  #       run: flutter pub get

  #     - name: Build for iOS
  #       run: flutter build ios --no-codesign --release

  #     - name: Upload Build Artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: iOS Application
  #         path: build/ios/iphoneos/*

  build-for-windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Get Dependencies
        run: flutter pub get

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Build for Windows
        run: flutter build windows --release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows Application
          path: build\windows\x64\runner\Release\*

  build-for-web:
    name: Build for Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Get Dependencies
        run: flutter pub get

      - name: Build for Web
        run: flutter build web --release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Web Application
          path: build/web/*

  upload-release:
    name: Upload Release
    needs: [
        build-for-linux,
        build-for-android,
        build-for-macos,
        # build-for-ios,
        build-for-windows,
        build-for-web,
      ]
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4

      - name: Get Timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "./**/*"
          tag: v${{ env.TIMESTAMP }}
          token: ${{ secrets.GITHUB_TOKEN }}
