# By Abdullah As-Sadeed

name: Build and Release
on:
  push:
    branches:
      - "main"
jobs:
  build-for-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y ninja-build libgtk-3-dev
        shell: bash

      - name: Run flutter doctor
        run: flutter doctor -v
        shell: bash

      - name: Get Dependencies
        run: flutter pub get
        shell: bash

      - name: Build for Linux
        run: flutter build linux --release --obfuscate --split-debug-info=./build/Debug_Symbols/Linux_x64/
        shell: bash

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux x64 Executable
          path: build/linux/x64/release/bundle/*

      - name: Upload Debug Symbols
        uses: actions/upload-artifact@v4
        with:
          name: Linux x64 Debug Symbols
          path: build/Debug_Symbols/Linux_x64/*

  build-for-android:
    name: Build for Android
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Run flutter doctor
        run: flutter doctor -v
        shell: bash

      - name: Get Dependencies
        run: flutter pub get
        shell: bash

      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> ./android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> ./android/key.properties
          echo "keyAlias=Bitscoper_Cyber_ToolBox" >> ./android/key.properties
          echo "storeFile=./KeyStore.jks" >> ./android/key.properties
        shell: bash

      - name: Create keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ./android/app/KeyStore.jks
        shell: bash

      - name: Build appbundle
        run: flutter build appbundle --release --obfuscate --split-debug-info=./build/Debug_Symbols/Android/appbundle/
        shell: bash

      - name: Build APKs
        run: flutter build apk --split-per-abi --release --obfuscate --split-debug-info=./build/Debug_Symbols/Android/APKs/
        shell: bash

      - name: Upload Build Artifacts (appbundle)
        uses: actions/upload-artifact@v4
        with:
          name: Android appbundle
          path: build/app/outputs/bundle/release/*

      - name: Upload Build Artifacts (APKs)
        uses: actions/upload-artifact@v4
        with:
          name: Android APKs
          path: build/app/outputs/flutter-apk/*

      - name: Upload Debug Symbols (appbundle)
        uses: actions/upload-artifact@v4
        with:
          name: Android appbundle Debug Symbols
          path: build/Debug_Symbols/Android/appbundle/*

      - name: Upload Debug Symbols (APKs)
        uses: actions/upload-artifact@v4
        with:
          name: Android APK Debug Symbols
          path: build/Debug_Symbols/Android/APKs/*

  build-for-macos:
    name: Build for macOS
    runs-on: macos-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Get Dependencies
        run: flutter pub get

      - name: Build for macOS
        run: flutter build macos --release --obfuscate --split-debug-info=./build/Debug_Symbols/macOS/

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macOS Executable
          path: build/macos/Build/Products/Release/*.app

      - name: Upload Debug Symbols
        uses: actions/upload-artifact@v4
        with:
          name: macOS Debug Symbols
          path: build/Debug_Symbols/macOS/*

  # build-for-ios:
  #   name: Build for iOS
  #   runs-on: macos-latest
  #   permissions:
  #       contents: read
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Install Pods
  #       run: |
  #         cd ios && pod install

  #     - name: Setup Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: "stable"

  #     - name: Run flutter doctor
  #       run: flutter doctor -v

  #     - name: Get Dependencies
  #       run: flutter pub get

  #     - name: Build for iOS
  #       run: flutter build ios --no-codesign --release --obfuscate --split-debug-info=./build/Debug_Symbols/iOS/

  #     - name: Upload Build Artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: iOS Application
  #         path: build/ios/iphoneos/*

  #     - name: Upload Debug Symbols
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: iOS Debug Symbols
  #         path: build/Debug_Symbols/iOS/*

  build-for-windows:
    name: Build for Windows
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Run flutter doctor
        run: flutter doctor -v

      - name: Get Dependencies
        run: flutter pub get

      - name: Build for Windows
        run: dart run msix:create # This includes: flutter build windows --release --obfuscate --split-debug-info=./build/Debug_Symbols/Windows/

      - name: Move MSIX Package
        run: |
          New-Item -ItemType Directory -Force -Path build\windows\x64\runner\Release_MSIX
          Move-Item -Path build\windows\x64\runner\Release\*.msix -Destination build\windows\x64\runner\Release_MSIX
        shell: powershell

      - name: Upload Build Artifacts (Executable)
        uses: actions/upload-artifact@v4
        with:
          name: Windows x64 Executable
          path: build\windows\x64\runner\Release\*

      - name: Upload Build Artifacts (MSIX Package)
        uses: actions/upload-artifact@v4
        with:
          name: Windows x64 MSIX Package
          path: build\windows\x64\runner\Release_MSIX\*.msix

      - name: Upload Debug Symbols
        uses: actions/upload-artifact@v4
        with:
          name: Windows x64 Debug Symbols
          path: build\Debug_Symbols\Windows\*

  build-for-web:
    name: Build for Web
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Run flutter doctor
        run: flutter doctor -v
        shell: bash

      - name: Get Dependencies
        run: flutter pub get
        shell: bash

      - name: Build for Web
        run: flutter build web --release
        shell: bash

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Web Application
          path: build/web/*

  upload-release:
    name: Upload Release
    needs: [
        build-for-linux,
        build-for-android,
        build-for-macos,
        # build-for-ios,
        build-for-windows,
        build-for-web,
      ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4

      - name: Archive Artifacts
        run: |
          zip -r Linux_x64_Executable.zip ./Linux\ x64\ Executable/*
          zip -r Android_appbundle.zip ./Android\ appbundle/*
          zip -r Android_APKs.zip ./Android\ APKs/*
          zip -r macOS_Executable.zip ./macOS\ Executable/*
          # zip -r iOS_Application.zip ./iOS\ Application/*
          zip -r Windows_x64_Executable.zip ./Windows\ x64\ Executable/*
          zip -r Windows_x64_MSIX_Package.zip ./Windows\ x64\ MSIX\ Package/*
          zip -r Web_Application.zip ./Web\ Application/*
          zip -r Linux_x64_Debug_Symbols.zip ./Linux\ x64\ Debug\ Symbols/*
          zip -r Android_appbundle_Debug_Symbols.zip ./Android\ appbundle\ Debug\ Symbols/*
          zip -r Android_APK_Debug_Symbols.zip ./Android\ APK\ Debug\ Symbols/*
          zip -r macOS_Debug_Symbols.zip ./macOS\ Debug\ Symbols/*
          # zip -r iOS_Debug_Symbols.zip ./iOS\ Debug\ Symbols/*
          zip -r Windows_x64_Debug_Symbols.zip ./Windows\ x64\ Debug\ Symbols/*
        shell: bash

      - name: Get Version
        run: echo "VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - name: Delete Existing Tag and Release (If Any)
        run: |
          TAG_NAME=v${{ env.VERSION }}
          RELEASE_ID=$(curl --silent --show-error --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases/tags/$TAG_NAME | jq '.id')
          if [ "$RELEASE_ID" != "null" ]; then
            curl --silent --show-error --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --request DELETE https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID
            git push --delete origin $TAG_NAME
          fi
        shell: bash

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "./*.zip"
          tag: v${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
